name: Add js_dependency analysis report in pull request comment
on:
  pull_request:

jobs:
  js_dependency:
    name: Export Mermaid by js_dependency
    runs-on: ubuntu-latest
    steps:
      - uses: junara/pull_request_comment_of_javascript_dependency_graph@main
        with:
          src_path: src
          child_analyze_level: 2
          parent_analyze_level: 2
          name_level: 2
          alias_paths: "@:./pages"
          exclude_output_names: "pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}

